# 02. Numpy

<p style="text-align: right;">
blackdew7@gmail.com<br>
Your name :
</p>

### 파이썬 실습시간 그 두번째!

Numpy는 데이터 과학을 위한 핵심 라이브러리입니다.
고성능 다차원 배열과 배열 연산을 위한 유용한 도구를 제공합니다

#### 실습목표
1. numpy library를 설치하고 사용할 수 있습니다.
2. numpy가 어떤 상황에서 쓰는 도구 인지 이해합니다. 
3. numpy array와 python list의 차이를 이해합니다. 
4. numpy를 이용하여 다양한 모양(shape)의 행렬 array를 만들고 계산할 수 있습니다. 
5. 파일로부터 데이터를 읽어 numpy 도구로 데이터 처리를 진행할 수 있습니다. 


## 00. 라이브러리 불러오기

In [0]:
# file update
from google.colab import files
uploaded = files.upload() # then browse, select the files. It's then uploaded

In [0]:
import numpy as np

In [0]:
# csv 파일 읽기
data = np.genfromtxt("Graduate_apply.csv", delimiter=",", names=True)
print(type(data))
print(data.shape)
print(data.ndim)


In [0]:
# 유용한 라이브러리
import time
import os

print(time.clock())
print(os.getcwd())

In [0]:
# 유용한 라이브러리 02

%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img = mpimg.imread('https://upload.wikimedia.org/wikipedia/commons/a/a4/TensorFlowLogo.png')
imgplot = plt.imshow(img)


## 01. Arrays 생성

In [0]:
# rank 1 array 생성
a = np.array([1, 2, 3])

print(type(a))            # "<class 'numpy.ndarray'>"
print(a.shape)            # "(3,)"
print(a[0], a[1], a[2])   # "1 2 3"

In [0]:
# rank 2 array 생성
b = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(b.shape)                     # "(2, 3)" 
print(b[0, 0], b[0, 1], b[1, 0])   # "1 2 4"


In [0]:
# 값 변경
a[0] = 5
print(a)

b[0, 0] = 5
print(b)

### reshape

In [0]:
# reshape
c = b.reshape((3, 2))
print(c.shape)                     # "(3, 2)"

In [0]:
# 64 * 64 * 3
arr = np.zeros((64, 64, 3))
print(arr.shape)

In [0]:
b = arr.reshape(64 * 64, 3) 
print(b.shape)

In [0]:
# -1은 1차와 2차의 크기를 16과 16으로 맞추고 남은 나머지라는 뜻입니다. 
c = arr.reshape(16, 16, -1) 
print(c.shape) 
# (64 * 64 * 3) / (16 * 16) = 48이므로 배열의 세 번째 차원의 크기는 48이 됩니다.

### 여러가지 array 생성함수
Numpy는 배열을 생성하는 다양한 함수를 제공합니다.

In [0]:
# 0으로 채워진 array 생성
a = np.zeros((2, 2))
print(a)              # "[[ 0.  0.]
                      #   [ 0.  0.]]"

In [0]:
# 1로 채워진 array 생성
b = np.ones((1, 2))
print(b)              # "[[ 1.  1.]]"

In [0]:
# 특정 값으로 채워진 array 생성
c = np.full((2, 2), 7.)  
print(c)               # "[[ 7.  7.]
                       #   [ 7.  7.]]"

In [0]:
# sequence array 생성
c = np.arange(0, 10)
print(c)

In [0]:
# 2x2 단위 행렬(identity matrix) 생성
d = np.eye(10)
print(d)
# [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
#  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

# 중요합니다. 기억해 둡시다! 
print(np.eye(10)[0])
print(np.eye(10)[2])
print(np.eye(10)[9])


In [0]:
# 랜덤값으로 채운 array 생성
e = np.random.random((2, 2))
print(e)
e = np.random.randint(16, size=(2, 2))
print(e)


In [0]:
# concatenate
c1 = np.arange(0, 10).reshape(2, 5)
c2 = np.arange(10, 20).reshape(2, 5)
print(c1)
print(c2)

print(np.concatenate((c1, c2), axis=0))
print(np.concatenate((c1, c2), axis=1))

#### list vs numpy array 속도 비교

In [0]:
import time 

li = list(range(1000000))

start = time.time()
li = [e * 2 for e in li]
print(time.time() - start)

np_li = np.arange(1000000)

start = time.time()
np_li *= 2
print(time.time() - start)


### 실습

In [0]:
a = [1, 2, 3, 4, 5, 6]

# a를 가지고 numpy array np_01을 생성하시오
np_01 = np.array(a)
print(np_01)

# np_01의 shape를 확인하시오.
print(np_01.shape)

# np_01의 shape를 (6, 1)로 변환하여 np_02에 넣으세요. 
np_02 = np_01.reshape(6, 1)

# np_01의 shape를 (1, 6)로 변환하여 np_03에 넣으세요. 
np_03 = np_01.reshape(1, 6)

# np_01의 shape를 (-1, 2)로 변환하여 np_04에 넣으세요. 
np_04 = np_01.reshape(-1, 2)

# np_01, np_02, np_03, np_04의 모양을 출력하고 
# shape와 실제 값의 모양을 확인하세요. 
print(np_01)
print(np_02)
print(np_03)
print(np_04)

# 0~255 랜덤값으로 채운 (28, 28) 
# numpy array를 생성하여 mnist_sample 변수에 담으세요.
mnist_sample = np.random.randint(256, size=(28, 28))
print(mnist_sample)

## 02. Array Indexing
데이터에 액세스하는 방법.

In [0]:
# array 생성 - shape (3, 4)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

#### _1. 정수 인덱스

In [0]:
# Integer array indexing
print(a[[0, 2]])

# "[1 4 5]"
print(a[[0, 1, 2], [0, 1, 0]])          
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

# 같은 위치 데이터를 여러번 사용할 수 있음
# "[2 2]"
print(a[[0, 0], [1, 1]])
print([a[0, 1], a[0, 1]])

#### _2. 슬라이스

In [0]:
# 행 
row_r2 = a[1:2, :]           # Rank 2
print(row_r2, row_r2.shape)  # "[[5 6 7 8]] (1, 4)"

# 열
col_r2 = a[:, 1:2]
print(col_r2, col_r2.shape)  # "[[ 2]
                             #   [ 6]
                             #   [10]] (3, 1)"

#### _3. 정수인덱스와 슬라이스를 같이 사용

In [0]:
# 행 
row_r1 = a[1, :]             # Rank 1
print(row_r1, row_r1.shape)  # "[5 6 7 8] (4,)"

# 열
col_r1 = a[:, 1]
print(col_r1, col_r1.shape)  # "[ 2  6 10] (3,)"

#### _4. boolean array indexing

In [0]:
a = np.array([[1, 2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])  # "[3 4 5 6]"
print(a[a > 2])     # "[3 4 5 6]"

#### 배열의 조각을 수정하면 원래 배열이 수정됩니다.

In [0]:
# array slice
# shape (2, 2) - 2x2 행렬
b = a[:2, 1:3]
b[0, 0] = 77     # b[0, 0] = a[0, 1]

print(a[0, 1])   # "77"

In [0]:
# array 생성 - shape (4, 3)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)

# element 선택 방식
b = np.arange(4) # [0, 1, 2, 3]
c = np.array([0, 2, 0, 1])
print(a[b, c])  # "[ 1  6  7 11]"

# 선택된 모든 element를 변경
a[b, c] += 10
print(a)

### 실습

In [0]:
li = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

# li로부터 다음의 모양을 갖는 numpy array를 np_arr을 생성하세요. 
# [[  1  2  3]
#  [  4  5  6]
#  [  7  8  9]
#  [ 10 11 12]]
print("1번문제")
np_arr = np.array([li[0:3], li[3:6], li[6:9], li[9:12]])
print(np_arr)
np_arr = np.array(li).reshape(-1, 3)
print(np_arr)

# np_arr의 shape를 확인하세요. 
print("2번문제")
print(np_arr.shape)

# 정수인덱싱을 사용하여 np_arr의 3행의 데이터를 아래의 shape 형태로 출력하세요.
# [7 8 9] - rank 1, shape (3, )
print("3번문제")
print(np_arr[2])
print(np_arr[2].shape)

# 정수인덱싱을 사용하여 np_arr의 2열의 데이터를 아래의 shape 형태로 출력하세요.
# [2 5 8 11] - rank 1, shape (4, )
print("4번문제")
print(np_arr[:, 1])
print(np_arr[:, 1].shape)

# 아래의 출력문이 어떤 값을 출력할 지 추측한 후에 결과를 확인하세요.
print("5번문제")
print(np_arr <= 5)
print(np_arr[np_arr <= 5])

# 위의 실습에서 선택된 element 값을 모두 2배로 만드세요.
print("6번문제")
np_arr[np_arr <= 5] *= 2

# np_arr을 출력해 봅니다.
print("7번문제")
print(np_arr)

# np_arr의 element중에 3의 배수인 element만 찾습니다. (3의 배수 찾는 법: x % 3 == 0)
print("8번문제")
print(np_arr[np_arr % 3 == 0])


## 03. Data 변환

In [0]:
# Numpy Array
x = np.array([1, 2])
print(type(x))             # <class ‘numpy.ndarray’>

# numpy.ndarray to list
y = x.tolist()
print(y)                    # [1, 2]
print(type(y))             # <class ‘list’>

In [0]:
x = np.array([1, 2])
print(x.dtype)             # "int64"

x = np.array([1.0, 2.0])
print(x.dtype)             # "float64"

x = np.array([1, 2], dtype=np.float64)   # 강제로 데이터 형식 지정
print(x.dtype)                           # "float64"
x

## 04. Array Math

In [0]:
x = np.array([[1, 2], 
              [3, 4]], dtype=np.float64)
y = np.array([[5, 6], 
              [7, 8]], dtype=np.float64)

# array 더하기
print(x + y)
print(np.add(x, y))

# array 빼기
print(x - y)
print(np.subtract(x, y))

# array 곱하기
print(x * y)
print(np.multiply(x, y))

# array 나누기
print(x / y)
print(np.divide(x, y))

# array 제곱근
print(np.sqrt(x))

In [0]:
# 행렬곱

x = np.array([[1, 2], 
              [3, 4]])
y = np.array([[5, 6], 
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# (2, ) * (2, ), 219
print(9 * 11 + 10 * 12)
print(v.dot(w))
# print(np.dot(v, w))

# (2, 2) * (2, ), rank 2 array
print(x)
print(v)
print("(1, 1): %d" % (1 * 9 + 2 * 10))
print("(1, 2): %d" % (3 * 9 + 4 * 10))
print(x.dot(v))
# print(np.dot(x, v))

# (2, 2) * (2, 2), rank 2 array
# [[19 22]
#  [43 50]]
print("(1, 1): %d" % (1 * 5 + 2 * 7))
print("(1, 2): %d" % (1 * 6 + 2 * 8))
print("(2, 1): %d" % (3 * 5 + 4 * 7))
print("(2, 2): %d" % (3 * 6 + 4 * 8))
print(x.dot(y))
# print(np.dot(x, y))

In [0]:
x = np.array([[1, 2], 
              [3, 4]])

# 합산
print(x.sum())          # "10"

# 열 합산
print(x.sum(axis=0))  # "[4 6]"

# 행 합산
print(x.sum(axis=1))  # "[3 7]"

In [0]:
x = np.array([[1, 2], [3, 4]])
print(x)

# 전치 행렬
print(x.T)

x = np.array([1, 2, 3, 4], ndmin=2) # ndmin 없이 해보기
print(x)   	    # "[[1 2 3 4]]"
print(x.shape)  # (1, 4)

# 전치 행렬
print(x.T)
            
# rank 1 에서는 변화가 없음
v = np.array([1, 2, 3])
print(v)    # "[1 2 3]"
print(v.T)  # "[1 2 3]"

### 실습

In [0]:
# 랜덤값으로 채운 (4, 3) numpy array를 생성하여 rand 변수에 담으세요.
rand = np.random.random((4, 3))

# rand를 출력하세요.
print(rand)

# rand를 열 방향으로 합산하세요.
print(rand.sum(axis=0))

# rand를 행 방향으로 합산하세요.
print(rand.sum(axis=1))

# rand의 전치 행렬을 출력하세요.
print(x.T)


## 05. Broadcasting

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

# x와 같은 shape의 0행렬 생성
y = np.empty_like(x)

# x의 행과 v의 모양이 같으므로 각 행에 v를 더한다.
for i in range(4):
    y[i, :] = x[i, :] + v

# y에 들어있는 결과 확인
print(y)

# 직접 더했을 때의 결과 확인
print(x + v)

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

# v를 여러개 쌓아 큰 배열의 모양으로 배열을 만든다.
vv = np.tile(v, (4, 1))
print(vv)

y = x + v
print(y)

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # broadcasting, v를 x의 각 행에 더한다.
print(y) 

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x * 2)

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([1, 2, 3])  # shape (3,)
print(x + v)

In [0]:
v = np.array([1, 2, 3])  # shape (3,)
w = np.array([4, 5])     # shape (2,)
print(v)
print(np.reshape(v, (3, 1)))
print(w)

In [0]:
v = np.array([1, 2, 3])  # shape (3,)
w = np.array([4, 5])     # shape (2,)
print(np.reshape(v, (3, 1)) * w)

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([4, 5])     # shape (2,)
print(x.T)
print(w)
print(x.T + w)
print((x.T + w).T)

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([4, 5])     # shape (2,)
print(np.reshape(w, (2, 1)))
print(x + np.reshape(w, (2, 1)))

### shuffle

In [0]:
data = np.genfromtxt("Graduate_apply.csv", delimiter=",", names=True)

# print(data[0:10])

# Shuffle
np.random.shuffle(data)

print(data[0:10])

### split

In [0]:
# Split
s1, s2, s3, s4 = data[:100], data[100:200], data[200:300], data[300:]
print(len(s1))
print(s1)
print(len(s2))
print(len(s3))
print(len(s4))


### 실습

In [0]:
# Graduate_apply.csv 파일을 읽어서 apply 변수에 담으세요. 
data = np.genfromtxt("Graduate_apply.csv", delimiter=",", names=True)

# apply의 element 갯수를 확인하세요. (400)
print(len(data))

# apply의 데이터 중 0 ~ 300 까지의 행은 train 변수에, 300 ~ 마지막 까지의 행은 test 변수에 담으세요.
train, test = data[:300], data[300:]
print(len(train))
print(len(test))

# train에 담겨있는 데이터를 suffle 하세요.
np.random.shuffle(train)
print(train[0:10])

## Numpy Documentation

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the <a href="http://docs.scipy.org/doc/numpy/reference/">numpy reference</a> to find out much more about numpy.